# frozen_string_literal: true

puts "Seeding chronic illnesses..."

chronic_illnesses = [
  { name: "Obesity", description: "A complex disease involving an excessive amount of body fat.", icon: "obesity.png", root_cause: "In Ayurveda, obesity, known as Medoroga, is primarily caused by an aggravated Kapha dosha, which leads to a slow metabolism and the accumulation of fat. A weakened digestive fire (Agni) also contributes by creating toxins (Ama) that clog the body's channels and disrupt metabolic processes." },
  { name: "Hypertension", description: "A condition in which the force of the blood against the artery walls is too high.", icon: "hypertension.png", root_cause: "Hypertension, or Rakta Gata Vata, is mainly caused by an imbalance in Vata and Pitta doshas. Aggravated Vata constricts the blood vessels, while excess Pitta leads to inflammation, both of which increase blood pressure." },
  { name: "Depression", description: "A mood disorder causing a persistent feeling of sadness and loss of interest.", icon: "depression.png", root_cause: "Depression, or Vishada, is primarily a Kapha imbalance, leading to heaviness and a lack of motivation. It can also be caused by an excess of Tamas, the mental quality of inertia and darkness, which clouds the mind and leads to feelings of hopelessness." },
  { name: "Diabetes", description: "A disease in which the body’s ability to produce or respond to the hormone insulin is impaired, resulting in abnormal metabolism of carbohydrates and elevated levels of glucose in the blood and urine.", icon: "diabetes.png", root_cause: "Known as Madhumeha, diabetes is primarily a Kapha disorder, caused by a sedentary lifestyle and a diet high in sweet, heavy foods. This imbalance weakens the digestive fire (Agni), leading to the formation of toxins (Ama) that disrupt insulin function." },
  { name: "Arthritis", description: "Inflammation of one or more joints, causing pain and stiffness that can worsen with age.", icon: "arthritis.png", root_cause: "Arthritis is mainly a Vata disorder, where an imbalance in Vata dosha leads to dryness and pain in the joints. The accumulation of toxins (Ama) from poor digestion further contributes to inflammation and stiffness." },
  { name: "Alzheimer's Disease", description: "A progressive disorder that causes brain cells to waste away (degenerate) and die.", icon: "alzheimers.png", root_cause: "In Ayurveda, Alzheimer's, or Smritinasha, is primarily caused by an imbalance of Vata dosha, which governs the nervous system. This imbalance disrupts memory and cognitive function, leading to the progressive degeneration of brain cells." },
  { name: "Asthma", description: "A condition in which your airways narrow and swell and may produce extra mucus.", icon: "asthma.png", root_cause: "Asthma, or Tamaka Shwasa, is caused by an imbalance of Vata and Kapha doshas, leading to the obstruction of respiratory channels. A weakened digestive fire (Agni) creates toxins (Ama) that mix with Kapha, creating mucus and blocking the flow of air." },
  { name: "Cancer", description: "A disease in which some of the body’s cells grow uncontrollably and spread to other parts of the body.", icon: "cancer.png", root_cause: "In Ayurveda, cancer, or Arbuda, is caused by an imbalance of all three doshas, leading to the uncontrolled proliferation of cells. The accumulation of toxins (Ama) from poor digestion also plays a key role by disrupting cellular intelligence and creating an environment for abnormal growth." },
  { name: "Cardiovascular Disease", description: "A general term for conditions affecting the heart or blood vessels.", icon: "cardiovascular.png", root_cause: "Cardiovascular disease, or Hridroga, is caused by an imbalance of the three doshas, which disrupts the normal functioning of the heart and blood vessels. The accumulation of toxins (Ama) from weak digestion is a key factor, leading to the blockage of arteries and compromising heart health." },
  { name: "Heart Disease", description: "Heart conditions that include diseased vessels, structural problems, and blood clots.", icon: "heart_disease.png", root_cause: "Heart disease is primarily caused by an imbalance of the three doshas, which affects the heart's rhythm, promotes inflammation, and leads to the accumulation of plaque in the arteries. Emotional stress and poor digestion, leading to the formation of toxins (Ama), are also significant contributing factors." },
  { name: "Chronic Kidney Disease", description: "A condition in which the kidneys are damaged and cannot filter blood as well as they should.", icon: "chronic_kidney_disease.png", root_cause: "Chronic Kidney Disease is caused by an imbalance of all three doshas, which impairs the filtering function of the kidneys. The accumulation of toxins (Ama) from improper digestion further obstructs the urinary channels, leading to progressive damage." },
  { name: "Chronic Obstructive Pulmonary Disease", description: "A chronic inflammatory lung disease that causes obstructed airflow from the lungs.", icon: "chronic_obstructive_pulmonary_disease.png", root_cause: "COPD is primarily a disorder of the Pranavaha Srotas (respiratory channels), caused by an imbalance of Vata and Kapha doshas. Excess Kapha leads to mucus and congestion, which obstructs the natural flow of Vata, leading to chronic cough and shortness of breath." },
  { name: "Stroke", description: "A disease that affects the arteries leading to and within the brain.", icon: "stroke.png", root_cause: "Known as Pakshaghata, a stroke is primarily a Vata disorder, where aggravated Vata constricts the blood vessels in the brain, obstructing the flow of vital energy. Imbalances in Pitta and Kapha can also contribute by causing inflammation and blockages in the arteries." },
  { name: "Addiction", description: "A treatable, chronic medical disease involving complex interactions among brain circuits, genetics, the environment, and an individual’s life experiences.", icon: "addiction.png", root_cause: "Addiction is seen as a state of imbalance in the doshas, where an individual seeks substances or behaviors to temporarily alleviate discomfort. It is also associated with an excess of Rajas (activity) and Tamas (inertia), which cloud the mind and lead to compulsive behaviors." },
  { name: "ALS (Lou Gehrig's Disease)", description: "A progressive neurodegenerative disease that affects nerve cells in the brain and the spinal cord.", icon: "als.png", root_cause: "ALS is primarily a Vata disorder, where a severe imbalance in Vata dosha leads to the degeneration of motor neurons. The obstruction of Vata by Kapha dosha also plays a role, leading to a loss of strength and control over the muscles." },
  { name: "Anxiety", description: "An emotion characterized by feelings of tension, worried thoughts and physical changes like increased blood pressure.", icon: "anxiety.png", root_cause: "Anxiety is primarily an imbalance of Vata dosha, which governs the nervous system and the flow of thoughts. An aggravated Vata leads to a state of mental and emotional instability, characterized by fear, worry, and restlessness." },
  { name: "Atrial Fibrillation", description: "An irregular and often very rapid heart rhythm (arrhythmia) that can lead to blood clots in the heart.", icon: "atrial_fibrillation.png", root_cause: "Atrial Fibrillation is mainly caused by a severe imbalance of Vata dosha, which disrupts the natural rhythm of the heart. Imbalances in Pitta and Kapha can also contribute by causing inflammation and blockages in the heart channels." },
  { name: "Autism Spectrum Disorders", description: "A developmental disability caused by differences in the brain.", icon: "autism.png", root_cause: "Autism is viewed as a complex neurodevelopmental condition rooted in a combination of genetic predispositions and digestive imbalances that disrupt the nervous system. An imbalance of the three doshas, particularly Vata, is a primary contributor, leading to hyperactivity, sensory sensitivities, and speech delays." },
  { name: "Crohn's Disease", description: "A type of inflammatory bowel disease (IBD) that causes inflammation of your digestive tract.", icon: "crohns_disease.png", root_cause: "Crohn's disease, or Grahani, is primarily caused by a weakened digestive fire (Agni), which leads to the formation of toxins (Ama). This, along with an imbalance of Pitta and Vata doshas, causes inflammation and damage to the intestinal lining." },
  { name: "Cystic Fibrosis", description: "A progressive, genetic disease that causes persistent lung infections and limits the ability to breathe over time.", icon: "cystic_fibrosis.png", root_cause: "Cystic Fibrosis is understood as a genetic disorder (Beeja Dosha) with a primary imbalance of Kapha dosha, leading to the production of thick mucus. An aggravated Vata dosha also contributes by drying out the mucus, making it difficult to expel." },
  { name: "Epilepsy", description: "A central nervous system (neurological) disorder in which brain activity becomes abnormal, causing seizures or periods of unusual behavior, sensations, and sometimes loss of awareness.", icon: "epilepsy.png", root_cause: "Epilepsy, or Apasmara, is primarily a Vata disorder, where an imbalance in Vata dosha disrupts the normal functioning of the nervous system, leading to seizures. Imbalances in Pitta and Kapha can also contribute by creating inflammation and blockages in the nervous system." },
  { name: "Hepatitis C", description: "A liver infection caused by the hepatitis C virus (HCV).", icon: "hepatitis_c.png", root_cause: "Hepatitis C is primarily a Pitta disorder, where an imbalance in Pitta dosha leads to inflammation and damage to the liver. A weakened digestive fire (Agni) and the accumulation of toxins (Ama) also contribute to the progression of the disease." },
  { name: "High Cholesterol", description: "A condition in which you have too many lipids (fats) in your blood.", icon: "high_cholesterol.png", root_cause: "High cholesterol is primarily a Kapha disorder, caused by an aggravated Kapha dosha leading to a sluggish metabolism and the accumulation of fatty tissues. A weakened digestive fire (Agni) also contributes by creating toxins (Ama) that clog the body's channels." },
  { name: "HIV/AIDS", description: "A chronic, potentially life-threatening condition caused by the human immunodeficiency virus (HIV). Acquired immunodeficiency syndrome (AIDS) is the late stage of infection with HIV.", icon: "hiv_aids.png", root_cause: "In Ayurveda, HIV/AIDS is understood as Ojakshaya, the depletion of Ojas, the body's vital essence and immunity. This depletion is caused by an imbalance of all three doshas and a process of reverse tissue wasting, leaving the body vulnerable to infections." },
  { name: "Osteoporosis", description: "A bone disease that develops when bone mineral density and bone mass decreases, or when the quality or structure of bone changes.", icon: "osteoporosis.png", root_cause: "Osteoporosis, or Asthi Dhatu Kshaya, is primarily a Vata disorder, where an imbalance in Vata dosha leads to the depletion of bone tissue. A weakened digestive fire (Agni) and the blockage of channels that nourish the bones also contribute to this condition." },
  { name: "Parkinson's Disease", description: "A progressive disorder that affects the nervous system and the parts of the body controlled by the nerves.", icon: "parkinsons_disease.png", root_cause: "Parkinson's disease, or Kampavata, is primarily a Vata disorder, where an imbalance in Vata dosha leads to the degeneration of nervous tissue (Majja Dhatu). The accumulation of toxins (Ama) in the nervous system also contributes to the progression of the disease." },
  { name: "Chronic Liver Disease", description: "A range of conditions that affect the liver, including Fatty Liver and Cirrhosis.", icon: "chronic_liver_disease.png", root_cause: "Chronic liver disease is primarily a Pitta disorder, where an imbalance in Pitta dosha leads to inflammation and damage to the liver. A weakened digestive fire (Agni) and the accumulation of toxins (Ama) also contribute to the progression of the disease." },
  { name: "Thyroid Disorders", description: "Conditions that affect the thyroid gland, such as Hypothyroidism and Hyperthyroidism.", icon: "thyroid.png", root_cause: "Thyroid disorders are caused by an imbalance of the doshas, particularly Pitta and Kapha, which affects the digestive fire (Agni). This imbalance disrupts the body's metabolism and leads to either an underactive (Kapha) or overactive (Pitta) thyroid." }
]

chronic_illnesses.each do |illness_data|
  illness = ChronicIllness.find_or_initialize_by(name: illness_data[:name])
  illness.description = illness_data[:description]
  illness.icon = illness_data[:icon]
  illness.save!
end

puts "Chronic illnesses seeded."
