# frozen_string_literal: true

puts "Seeding chronic illnesses..."

chronic_illnesses = [
  { name: "Obesity", description: "A complex disease involving an excessive amount of body fat.", icon: "obesity.png", root_cause: "Obesity arises from kapha imbalance (excess earth and water), weak agni (digestive fire), and accumulation of ama (toxins) from improper diet and lifestyle." },
  { name: "Hypertension", description: "A condition in which the force of the blood against the artery walls is too high.", icon: "hypertension.png", root_cause: "Hypertension develops from aggravated pitta (fire) and vata (air) disturbing circulation, often fueled by stress and poor digestion." },
  { name: "Depression", description: "A mood disorder causing a persistent feeling of sadness and loss of interest.", icon: "depression.png", root_cause: "Depression is rooted in vata imbalance (air element) in the nervous system combined with kapha stagnation (heaviness) and impaired prana flow (life-force energy)." },
  { name: "Diabetes", description: "A disease in which the body’s ability to produce or respond to the hormone insulin is impaired, resulting in abnormal metabolism of carbohydrates and elevated levels of glucose in the blood and urine.", icon: "diabetes.png", root_cause: "Diabetes (Madhumeha, 'honey urine') arises from kapha (earth-water) and vata (air) imbalance, weak agni (digestive fire), and excess sweet, heavy foods leading to ojas depletion (vital essence)." },
  { name: "Arthritis", description: "Inflammation of one or more joints, causing pain and stiffness that can worsen with age.", icon: "arthritis.png", root_cause: "Arthritis stems from vata aggravation (dryness and movement) in the joints, leading to pain and ama (toxins) accumulation causing inflammation." },
  { name: "Alzheimer's Disease", description: "A progressive disorder that causes brain cells to waste away (degenerate) and die.", icon: "alzheimers.png", root_cause: "Alzheimer’s is caused by vata derangement (air imbalance) in majja dhatu (nervous tissue), leading to depletion of memory and ojas (vital essence)." },
  { name: "Asthma", description: "A condition in which your airways narrow and swell and may produce extra mucus.", icon: "asthma.png", root_cause: "Asthma arises from kapha (mucus, heaviness) blocking the respiratory channels with vata (air) aggravation disturbing prana (life-force) flow." },
  { name: "Cancer", description: "A disease in which some of the body’s cells grow uncontrollably and spread to other parts of the body.", icon: "cancer.png", root_cause: "Cancer is linked to severe dosha imbalance (vata, pitta, kapha), impaired agni (digestive fire), and deep-seated ama (toxins) disrupting cellular intelligence." },
  { name: "Cardiovascular Disease", description: "A general term for conditions affecting the heart or blood vessels.", icon: "cardiovascular.png", root_cause: "Cardiovascular disease arises from vata (air) and kapha (heaviness) imbalance, impaired circulation, and accumulation of ama (toxins) in the vessels." },
  { name: "Heart Disease", description: "Heart conditions that include diseased vessels, structural problems, and blood clots.", icon: "heart_disease.png", root_cause: "Heart disease comes from pitta (fire) and kapha (earth-water) imbalance, clogged srotas (body channels), and weakening of ojas (vital essence)." },
  { name: "Chronic Kidney Disease", description: "A condition in which the kidneys are damaged and cannot filter blood as well as they should.", icon: "chronic_kidney_disease.png", root_cause: "Kidney disease is caused by vata (air) and kapha (earth-water) aggravation obstructing mutravaha srotas (urinary channels) with accumulated ama (toxins)." },
  { name: "Chronic Obstructive Pulmonary Disease", description: "A chronic inflammatory lung disease that causes obstructed airflow from the lungs.", icon: "chronic_obstructive_pulmonary_disease.png", root_cause: "COPD stems from kapha (mucus) obstruction and vata (air) derangement in pranavaha srotas (respiratory channels), aggravated by weak agni (digestive fire)." },
  { name: "Stroke", description: "A disease that affects the arteries leading to and within the brain.", icon: "stroke.png", root_cause: "Stroke results from vata aggravation (air imbalance) in the nervous system and blocked srotas (channels) due to kapha (heaviness) and ama (toxins)." },
  { name: "Addiction", description: "A treatable, chronic medical disease involving complex interactions among brain circuits, genetics, the environment, and an individual’s life experiences.", icon: "addiction.png", root_cause: "Addiction arises from vata imbalance (air element) in the mind and majja dhatu (nervous tissue), with disturbed sattva (clarity) and impaired ojas (vital essence)." },
  { name: "ALS (Lou Gehrig's Disease)", description: "A progressive neurodegenerative disease that affects nerve cells in the brain and the spinal cord.", icon: "als.png", root_cause: "ALS develops from aggravated vata (air) causing degeneration of majja dhatu (nervous tissue) and loss of muscular support." },
  { name: "Anxiety", description: "An emotion characterized by feelings of tension, worried thoughts and physical changes like increased blood pressure.", icon: "anxiety.png", root_cause: "Anxiety is rooted in vata imbalance (air element) in the nervous system, leading to instability of prana (life-force) and manas (mind)." },
  { name: "Atrial Fibrillation", description: "An irregular and often very rapid heart rhythm (arrhythmia) that can lead to blood clots in the heart.", icon: "atrial_fibrillation.png", root_cause: "Atrial fibrillation arises from vata aggravation (air imbalance) in hridaya (heart) channels disturbed by pitta (fire) or kapha (mucus) obstruction." },
  { name: "Autism Spectrum Disorders", description: "A developmental disability caused by differences in the brain.", icon: "autism.png", root_cause: "Autism is linked to vata imbalance (air) in majja dhatu (nervous tissue) and impaired manovaha srotas (mental channels), with disturbed sattva (clarity)." },
  { name: "Crohn's Disease", description: "A type of inflammatory bowel disease (IBD) that causes inflammation of your digestive tract.", icon: "crohns_disease.png", root_cause: "Crohn’s disease comes from aggravated pitta (fire) and vata (air) disturbing agni (digestive fire) and damaging the intestines." },
  { name: "Cystic Fibrosis", description: "A progressive, genetic disease that causes persistent lung infections and limits the ability to breathe over time.", icon: "cystic_fibrosis.png", root_cause: "Cystic fibrosis reflects kapha (mucus) aggravation with ama (toxins) blocking pranavaha srotas (respiratory channels) and impaired ojas (vital essence) protection." },
  { name: "Epilepsy", description: "A central nervous system (neurological) disorder in which brain activity becomes abnormal, causing seizures or periods of unusual behavior, sensations, and sometimes loss of awareness.", icon: "epilepsy.png", root_cause: "Epilepsy arises from vata imbalance (air) in majja dhatu (nervous tissue) disturbing prana vayu (nerve impulses) and mental stability." },
  { name: "Hepatitis C", description: "A liver infection caused by the hepatitis C virus (HCV).", icon: "hepatitis_c.png", root_cause: "Hepatitis C is caused by aggravated pitta (fire) damaging rakta dhatu (blood tissue) and the liver’s channels." },
  { name: "High Cholesterol", description: "A condition in which you have too many lipids (fats) in your blood.", icon: "high_cholesterol.png", root_cause: "High cholesterol stems from kapha imbalance (heaviness), weak agni (digestive fire), and accumulation of ama (toxins) in the blood channels." },
  { name: "HIV/AIDS", description: "A chronic, potentially life-threatening condition caused by the human immunodeficiency virus (HIV). Acquired immunodeficiency syndrome (AIDS) is the late stage of infection with HIV.", icon: "hiv_aids.png", root_cause: "HIV/AIDS arises from depleted ojas (vital essence), weak agni (digestive fire), and aggravated doshas compromising immunity." },
  { name: "Osteoporosis", description: "A bone disease that develops when bone mineral density and bone mass decreases, or when the quality or structure of bone changes.", icon: "osteoporosis.png", root_cause: "Osteoporosis arises from vata aggravation (air imbalance) and dhatu kshaya (tissue depletion) of asthi dhatu (bone tissue)." },
  { name: "Parkinson's Disease", description: "A progressive disorder that affects the nervous system and the parts of the body controlled by the nerves.", icon: "parkinsons_disease.png", root_cause: "Parkinson’s disease comes from aggravated vata (air imbalance) affecting majja dhatu (nervous tissue), leading to tremors and stiffness." },
  { name: "Chronic Liver Disease", description: "A range of conditions that affect the liver, including Fatty Liver and Cirrhosis.", icon: "chronic_liver_disease.png", root_cause: "Chronic liver disease is due to pitta aggravation (fire imbalance) with kapha (mucus) obstruction and ama (toxins) accumulation in the liver channels." },
  { name: "Thyroid Disorders", description: "Conditions that affect the thyroid gland, such as Hypothyroidism and Hyperthyroidism.", icon: "thyroid.png", root_cause: "Thyroid disorders arise from kapha (heaviness) and vata (air) imbalance in metabolism and impaired agni (digestive fire) regulating growth and energy." }
]

chronic_illnesses.each do |illness_data|
  illness = ChronicIllness.find_or_initialize_by(name: illness_data[:name])
  illness.description = illness_data[:description]
  illness.icon = illness_data[:icon]
  illness.root_cause = illness_data[:root_cause]
  illness.save!
end

puts "Chronic illnesses seeded."
