default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  primary:
    adapter: sqlite3
    database: /rails/storage/production.sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
  cache:
    adapter: sqlite3
    database: /rails/storage/production_cache.sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
    migrations_paths: db/cache_migrate
  queue:
    adapter: sqlite3
    database: /rails/storage/production_queue.sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
    migrations_paths: db/queue_migrate
  cable:
    adapter: sqlite3
    database: /rails/storage/production_cable.sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
    migrations_paths: db/cable_migrate