default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/development_primary.sqlite3
  cache:
    <<: *default
    database: db/development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: db/development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: db/development_cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: db/test_primary.sqlite3
  cache:
    <<: *default
    database: db/test_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: db/test_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: db/test_cable.sqlite3
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: /rails/storage/production.sqlite3
  cache:
    <<: *default
    database: /rails/storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: /rails/storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: /rails/storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
