service: ancientherb
image: bryanprz00/ancientherb

servers:
  web:
    hosts:
      - 162.243.220.201

registry:
  username: bryanprz00
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

volumes:
  - "/var/lib/ancientherb/storage:/rails/storage"

env:
  clear:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY

proxy:
  app_port: 3000
  healthcheck:
    path: /up
    interval: 10
    timeout: 10

readiness_delay: 15
