service: ancientherb
image: bryanprz00/ancientherb

servers:
  web:
    hosts:
      - 138.197.45.148
    hooks:
      post-deploy:
        - bundle exec rails migrate_all

registry:
  username: bryanprz00
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64
    - arm64

volumes:
  - "/var/lib/ancientherb/storage:/rails/storage"

env:
  clear:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY

proxy:
  ssl: true
  host: ancientherb.health
  app_port: 3000
  healthcheck:
    path: /up
    interval: 10
    timeout: 10
readiness_delay: 30
