service: ancientherb
image: bryanprz00/ancientherb

release_command: RAILS_ENV=production bin/rails db:migrate DATABASE=queue

accessories:
  ollama:
    image: ollama/ollama:latest
    host: 138.197.45.148 # Deploy on the same server as the web app
    volumes:
      - "/var/lib/ollama:/root/.ollama" # Persistent storage for models
    env:
      clear:
        OLLAMA_HOST: 0.0.0.0 # Allow external connections

servers:
  web:
    hosts:
      - 138.197.45.148
  worker: # New worker role
    hosts:
      - 138.197.45.148 # Deploy on the same server as the web app
    cmd: bundle exec rails solid_queue:start

registry:
  username: bryanprz00
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64
    - arm64

volumes:
  - "/var/lib/ancientherb/storage:/rails/storage"

env:
  clear:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY
    - GCP_PROJECT_ID
    - GCS_BUCKET_NAME
    - GCS_KEYFILE_JSON
    - SECRET_KEY_BASE

proxy:
  ssl: true
  host: ancientherb.health
  app_port: 3000
  healthcheck:
    path: /up
    interval: 10
    timeout: 10
readiness_delay: 30




