service: ancientherb
image: bryanprz00/ancientherb

servers:
  web:
    hosts:
      - 162.243.220.201

registry:
  username: bryanprz00
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64
    - arm64

volumes:
  - "/var/lib/ancientherb/storage:/rails/storage"

env:
  clear:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY

proxy:
  app_port: 3000
  deploy_timeout: 60s     # Add this
  drain_timeout: 30s      # Add this
  healthcheck:
    path: /up
    interval: 10s         # Add 's' suffix
    timeout: 10s          # Add 's' suffix
    max_attempts: 6       # Add this
readiness_delay: 30s      # Add 's' suffix and increase from 15



# proxy:
#   app_port: 3000
#   healthcheck:
#     path: /up
#     interval: 10
#     timeout: 10
#
# readiness_delay: 15
