# Demo deployment configuration (sanitized)
# This is an example configuration for portfolio demonstration

service: mindmetrics
image: your-dockerhub-username/mindmetrics

# Example configuration - update with your values
servers:
  web:
    hosts:
      - your-server-ip
  worker:
    hosts:
      - your-server-ip
    cmd: bundle exec rails solid_queue:start

registry:
  username: your-registry-username
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64
    - arm64

volumes:
  - "/var/lib/mindmetrics/storage:/rails/storage"

env:
  clear:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE

proxy:
  ssl: true
  host: your-domain.com
  app_port: 3000
  healthcheck:
    path: /up
    interval: 10
    timeout: 10
readiness_delay: 30




