test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google_social_posts:
  service: GCS
  project: <%= Rails.application.credentials.gcs[:project_id] %>
  bucket: <%= Rails.application.credentials.gcs[:bucket] %>
  credentials: <%= Rails.application.credentials.gcs[:credentials].to_json %>

google_avatars:
  service: GCS
  project: <%= Rails.application.credentials.gcs[:project_id] %>
  bucket: ancientherb-avatars
  credentials: <%= Rails.application.credentials.gcs[:credentials].to_json %>

google_message_attachments:
  service: GCS
  project: <%= Rails.application.credentials.gcs[:project_id] %>
  bucket: ancientherb-message-attachments
  credentials: <%= Rails.application.credentials.gcs[:credentials].to_json %>
